In [1]:
pip install pandas

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (2.3.3)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from pandas) (2025.3)
Requirement already satisfied: numpy>=1.22.4 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/dennis/Library/Python/3.9/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /Users/dennis/Library/Python/3.9/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
WARNING: You are using pip version 21.1.1; however, version 25.3 is available.
You should consider upgrading via the '/Library/Frameworks/Python.framework/Versions/3.9/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install numpy

Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (2.0.2)
WARNING: You are using pip version 21.1.1; however, version 25.3 is available.
You should consider upgrading via the '/Library/Frameworks/Python.framework/Versions/3.9/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd

# Read the CSV into a DataFrame
df = pd.read_csv('pp-complete.csv', header=None)

# Display the result
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,{3DD6D1E9-68E3-4646-8682-FD7DB9884D97},76000,1995-11-30 00:00,RG21 5RX,T,N,F,1,NaN,LANSLEY ROAD,BASINGSTOKE,BASINGSTOKE,BASINGSTOKE AND DEANE,HAMPSHIRE,A,A
1,{82899FB9-496F-4FA3-8249-F6811A87F376},48000,1995-01-27 00:00,LA1 1SY,T,N,F,26,NaN,PORTLAND STREET,LANCASTER,LANCASTER,LANCASTER,LANCASHIRE,A,A
2,{B7B48D70-7FEB-437B-9EAC-F681547AB62F},59000,1995-11-17 00:00,PL3 6DR,S,N,F,26,NaN,FAIRVIEW AVENUE,PLYMOUTH,PLYMOUTH,PLYMOUTH,DEVON,A,A
3,{B75382B6-4B58-4284-A890-FD7E1C297E5D},69950,1995-04-06 00:00,TN2 3HU,S,N,F,227,NaN,GREGGS WOOD ROAD,TUNBRIDGE WELLS,TUNBRIDGE WELLS,TUNBRIDGE WELLS,KENT,A,A
4,{B6F968FF-CEB2-4A18-B212-EF6CFE08958D},57850,1995-12-15 00:00,HX7 5DY,S,Y,F,3,NaN,STREAMSIDE FOLD,MYTHOLMROYD,HEBDEN BRIDGE,CALDERDALE,WEST YORKSHIRE,A,A

In [4]:
# List of official column names for the Price Paid dataset
df.columns = [
    'TID', 'Price', 'Date', 'Postcode', 'Type', 'New_Build', 
    'Tenure', 'PAON', 'SAON', 'Street', 'Locality', 
    'Town', 'District', 'County', 'Category', 'Status'
]

# Verify the changes
df.head()

,TID,Price,Date,Postcode,Type,New_Build,Tenure,PAON,SAON,Street,Locality,Town,District,County,Category,Status
0,{3DD6D1E9-68E3-4646-8682-FD7DB9884D97},76000,1995-11-30 00:00,RG21 5RX,T,N,F,1,NaN,LANSLEY ROAD,BASINGSTOKE,BASINGSTOKE,BASINGSTOKE AND DEANE,HAMPSHIRE,A,A
1,{82899FB9-496F-4FA3-8249-F6811A87F376},48000,1995-01-27 00:00,LA1 1SY,T,N,F,26,NaN,PORTLAND STREET,LANCASTER,LANCASTER,LANCASTER,LANCASHIRE,A,A
2,{B7B48D70-7FEB-437B-9EAC-F681547AB62F},59000,1995-11-17 00:00,PL3 6DR,S,N,F,26,NaN,FAIRVIEW AVENUE,PLYMOUTH,PLYMOUTH,PLYMOUTH,DEVON,A,A
3,{B75382B6-4B58-4284-A890-FD7E1C297E5D},69950,1995-04-06 00:00,TN2 3HU,S,N,F,227,NaN,GREGGS WOOD ROAD,TUNBRIDGE WELLS,TUNBRIDGE WELLS,TUNBRIDGE WELLS,KENT,A,A
4,{B6F968FF-CEB2-4A18-B212-EF6CFE08958D},57850,1995-12-15 00:00,HX7 5DY,S,Y,F,3,NaN,STREAMSIDE FOLD,MYTHOLMROYD,HEBDEN BRIDGE,CALDERDALE,WEST YORKSHIRE,A,A

In [5]:
# Filter the DataFrame for London
london_df = df[df['Town'] == 'LONDON']

# Display the first few rows of the filtered data
london_df.head()

# Optional: Check how many records were found
print(f"Total records found in London: {len(london_df)}")

Total records found in London: 2340863

In [6]:
len(df)

30813304

In [7]:
london_df.head()

,TID,Price,Date,Postcode,Type,New_Build,Tenure,PAON,SAON,Street,Locality,Town,District,County,Category,Status
27,{6C8EB1A4-BCF4-4384-89F5-EF6D2A611CAE},54500,1995-07-14 00:00,SE22 9HB,F,N,L,12B,NaN,CRYSTAL PALACE ROAD,LONDON,LONDON,SOUTHWARK,GREATER LONDON,A,A
30,{B47417FA-B996-47C8-92F4-EF6D532B3C0B},80000,1995-09-08 00:00,N20 0HU,S,N,F,1,NaN,CAMERON CLOSE,LONDON,LONDON,BARNET,GREATER LONDON,A,A
44,{A2EA1712-0C79-4959-A7AF-F2F141ADF9C9},83000,1995-07-27 00:00,SW12 0ND,F,N,L,146,NaN,WEIR ROAD,LONDON,LONDON,LAMBETH,GREATER LONDON,A,A
72,{FC2FDDAE-C57F-430C-8AEC-F9FC59D8A148},71500,1995-03-07 00:00,SW14 7DJ,F,N,L,20,NaN,DEANHILL COURT,LONDON,LONDON,RICHMOND UPON THAMES,GREATER LONDON,A,A
78,{430BBDD7-7D41-46AF-89AC-F6820BC87DFC},80000,1995-01-27 00:00,N18 1AW,T,N,F,118,NaN,PASTEUR GARDENS,LONDON,LONDON,ENFIELD,GREATER LONDON,A,A

In [8]:
london_df.to_csv('london_df.csv')